import json

baseOreDataDict = {'Arkonor': {'compressed_type_id': 28367,
                               'compressed_volume': 8.8,
                               'type_id': 22,
                               'unit_type': 'ore',
                               'volume': 16},
                   'Azure Plagioclase': {'compressed_type_id': 28421,
                                         'compressed_volume': 0.15,
                                         'type_id': 17455,
                                         'unit_type': 'ore',
                                         'volume': 0.35},
                   'Bistot': {'compressed_type_id': 28388,
                              'compressed_volume': 4.4,
                              'type_id': 1223,
                              'unit_type': 'ore',
                              'volume': 16},
                   'Bitumens': {'compressed_type_id': 45492,
                                'compressed_volume': 10,
                                'type_id': 45492,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Blue Ice': {'compressed_type_id': 28433,
                                'compressed_volume': 100.0,
                                'type_id': 16264,
                                'unit_type': 'ice',
                                'volume': 1000},
                   'Bountiful Loparite': {'compressed_type_id': 46316,
                                          'compressed_volume': 10,
                                          'type_id': 46316,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Bountiful Monazite': {'compressed_type_id': 46314,
                                          'compressed_volume': 10,
                                          'type_id': 46314,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Bountiful Xenotime': {'compressed_type_id': 46312,
                                          'compressed_volume': 10,
                                          'type_id': 46312,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Bountiful Ytterbite': {'compressed_type_id': 46318,
                                           'compressed_volume': 10,
                                           'type_id': 46318,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Bright Spodumain': {'compressed_type_id': 28418,
                                        'compressed_volume': 28.0,
                                        'type_id': 17466,
                                        'unit_type': 'ore',
                                        'volume': 16},
                   'Brilliant Gneiss': {'compressed_type_id': 46695,
                                        'compressed_volume': 1.8,
                                        'type_id': 46679,
                                        'unit_type': 'ore',
                                        'volume': 5},
                   'Brimful Bitumens': {'compressed_type_id': 46284,
                                        'compressed_volume': 10,
                                        'type_id': 46284,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Brimful Coesite': {'compressed_type_id': 46286,
                                       'compressed_volume': 10,
                                       'type_id': 46286,
                                       'unit_type': 'moon_goo',
                                       'volume': 10},
                   'Brimful Sylvite': {'compressed_type_id': 46282,
                                       'compressed_volume': 10,
                                       'type_id': 46282,
                                       'unit_type': 'moon_goo',
                                       'volume': 10},
                   'Brimful Zeolites': {'compressed_type_id': 46280,
                                        'compressed_volume': 10,
                                        'type_id': 46280,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Carnotite': {'compressed_type_id': 45502,
                                 'compressed_volume': 10,
                                 'type_id': 45502,
                                 'unit_type': 'moon_goo',
                                 'volume': 10},
                   'Chromite': {'compressed_type_id': 45501,
                                'compressed_volume': 10,
                                'type_id': 45501,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Cinnabar': {'compressed_type_id': 45506,
                                'compressed_volume': 10,
                                'type_id': 45506,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Clear Icicle': {'compressed_type_id': 28434,
                                    'compressed_volume': 100.0,
                                    'type_id': 16262,
                                    'unit_type': 'ice',
                                    'volume': 1000},
                   'Cobaltite': {'compressed_type_id': 45494,
                                 'compressed_volume': 10,
                                 'type_id': 45494,
                                 'unit_type': 'moon_goo',
                                 'volume': 10},
                   'Coesite': {'compressed_type_id': 45493,
                               'compressed_volume': 10,
                               'type_id': 45493,
                               'unit_type': 'moon_goo',
                               'volume': 10},
                   'Concentrated Veldspar': {'compressed_type_id': 28430,
                                             'compressed_volume': 0.15,
                                             'type_id': 17470,
                                             'unit_type': 'ore',
                                             'volume': 0.1},
                   'Condensed Scordite': {'compressed_type_id': 28427,
                                          'compressed_volume': 0.19,
                                          'type_id': 17463,
                                          'unit_type': 'ore',
                                          'volume': 0.15},
                   'Copious Cobaltite': {'compressed_type_id': 46288,
                                         'compressed_volume': 10,
                                         'type_id': 46288,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Copious Euxenite': {'compressed_type_id': 46290,
                                        'compressed_volume': 10,
                                        'type_id': 46290,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Copious Scheelite': {'compressed_type_id': 46294,
                                         'compressed_volume': 10,
                                         'type_id': 46294,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Copious Titanite': {'compressed_type_id': 46292,
                                        'compressed_volume': 10,
                                        'type_id': 46292,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Crimson Arkonor': {'compressed_type_id': 28385,
                                       'compressed_volume': 8.8,
                                       'type_id': 17425,
                                       'unit_type': 'ore',
                                       'volume': 16},
                   'Crokite': {'compressed_type_id': 28391,
                               'compressed_volume': 7.81,
                               'type_id': 1225,
                               'unit_type': 'ore',
                               'volume': 16},
                   'Crystalline Crokite': {'compressed_type_id': 28392,
                                           'compressed_volume': 7.81,
                                           'type_id': 17433,
                                           'unit_type': 'ore',
                                           'volume': 16},
                   'Cubic Bistot': {'compressed_type_id': 46692,
                                    'compressed_volume': 4.4,
                                    'type_id': 46676,
                                    'unit_type': 'ore',
                                    'volume': 16},
                   'Dark Glitter': {'compressed_type_id': 28435,
                                    'compressed_volume': 100.0,
                                    'type_id': 16267,
                                    'unit_type': 'ice',
                                    'volume': 1000},
                   'Dark Ochre': {'compressed_type_id': 28394,
                                  'compressed_volume': 4.2,
                                  'type_id': 1232,
                                  'unit_type': 'ore',
                                  'volume': 8},
                   'Dazzling Spodumain': {'compressed_type_id': 46704,
                                          'compressed_volume': 28.0,
                                          'type_id': 46688,
                                          'unit_type': 'ore',
                                          'volume': 16},
                   'Dense Veldspar': {'compressed_type_id': 28431,
                                      'compressed_volume': 0.15,
                                      'type_id': 17471,
                                      'unit_type': 'ore',
                                      'volume': 0.1},
                   'Enriched Clear Icicle': {'compressed_type_id': 28436,
                                             'compressed_volume': 100.0,
                                             'type_id': 17978,
                                             'unit_type': 'ice',
                                             'volume': 1000},
                   'Euxenite': {'compressed_type_id': 45495,
                                'compressed_volume': 10,
                                'type_id': 45495,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Fiery Kernite': {'compressed_type_id': 28409,
                                     'compressed_volume': 0.19,
                                     'type_id': 17453,
                                     'unit_type': 'ore',
                                     'volume': 1.2},
                   'Flawless Arkonor': {'compressed_type_id': 46691,
                                        'compressed_volume': 8.8,
                                        'type_id': 46678,
                                        'unit_type': 'ore',
                                        'volume': 16},
                   'Gelidus': {'compressed_type_id': 28437,
                               'compressed_volume': 100.0,
                               'type_id': 16268,
                               'unit_type': 'ice',
                               'volume': 1000},
                   'Glacial Mass': {'compressed_type_id': 28438,
                                    'compressed_volume': 100.0,
                                    'type_id': 16263,
                                    'unit_type': 'ice',
                                    'volume': 1000},
                   'Glare Crust': {'compressed_type_id': 28439,
                                   'compressed_volume': 100.0,
                                   'type_id': 16266,
                                   'unit_type': 'ice',
                                   'volume': 1000},
                   'Glazed Hedbergite': {'compressed_type_id': 28400,
                                         'compressed_volume': 0.47,
                                         'type_id': 17441,
                                         'unit_type': 'ore',
                                         'volume': 3},
                   'Gleaming Spodumain': {'compressed_type_id': 28419,
                                          'compressed_volume': 28.0,
                                          'type_id': 17467,
                                          'unit_type': 'ore',
                                          'volume': 16},
                   'Glistening Bitumens': {'compressed_type_id': 46285,
                                           'compressed_volume': 10,
                                           'type_id': 46285,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Glistening Coesite': {'compressed_type_id': 46287,
                                          'compressed_volume': 10,
                                          'type_id': 46287,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Glistening Sylvite': {'compressed_type_id': 46283,
                                          'compressed_volume': 10,
                                          'type_id': 46283,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Glistening Zeolites': {'compressed_type_id': 46281,
                                           'compressed_volume': 10,
                                           'type_id': 46281,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Glossy Scordite': {'compressed_type_id': 46703,
                                       'compressed_volume': 0.19,
                                       'type_id': 46687,
                                       'unit_type': 'ore',
                                       'volume': 0.15},
                   'Glowing Carnotite': {'compressed_type_id': 46305,
                                         'compressed_volume': 10,
                                         'type_id': 46305,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Glowing Cinnabar': {'compressed_type_id': 46311,
                                        'compressed_volume': 10,
                                        'type_id': 46311,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Glowing Pollucite': {'compressed_type_id': 46309,
                                         'compressed_volume': 10,
                                         'type_id': 46309,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Glowing Zircon': {'compressed_type_id': 46307,
                                      'compressed_volume': 10,
                                      'type_id': 46307,
                                      'unit_type': 'moon_goo',
                                      'volume': 10},
                   'Gneiss': {'compressed_type_id': 28397,
                              'compressed_volume': 1.8,
                              'type_id': 1229,
                              'unit_type': 'ore',
                              'volume': 5},
                   'Golden Omber': {'compressed_type_id': 28415,
                                    'compressed_volume': 0.3,
                                    'type_id': 17868,
                                    'unit_type': 'ore',
                                    'volume': 0.6},
                   'Hedbergite': {'compressed_type_id': 28401,
                                  'compressed_volume': 0.47,
                                  'type_id': 21,
                                  'unit_type': 'ore',
                                  'volume': 3},
                   'Hemorphite': {'compressed_type_id': 28403,
                                  'compressed_volume': 0.86,
                                  'type_id': 1231,
                                  'unit_type': 'ore',
                                  'volume': 3},
                   'Immaculate Jaspet': {'compressed_type_id': 46698,
                                         'compressed_volume': 0.15,
                                         'type_id': 46682,
                                         'unit_type': 'ore',
                                         'volume': 2},
                   'Iridescent Gneiss': {'compressed_type_id': 28398,
                                         'compressed_volume': 1.8,
                                         'type_id': 17865,
                                         'unit_type': 'ore',
                                         'volume': 5},
                   'Jaspet': {'compressed_type_id': 28406,
                              'compressed_volume': 0.15,
                              'type_id': 1226,
                              'unit_type': 'ore',
                              'volume': 2},
                   'Jet Ochre': {'compressed_type_id': 46694,
                                 'compressed_volume': 4.2,
                                 'type_id': 46675,
                                 'unit_type': 'ore',
                                 'volume': 8},
                   'Kernite': {'compressed_type_id': 28410,
                               'compressed_volume': 0.19,
                               'type_id': 20,
                               'unit_type': 'ore',
                               'volume': 1.2},
                   'Krystallos': {'compressed_type_id': 28440,
                                  'compressed_volume': 100.0,
                                  'type_id': 16269,
                                  'unit_type': 'ice',
                                  'volume': 1000},
                   'Lavish Chromite': {'compressed_type_id': 46302,
                                       'compressed_volume': 10,
                                       'type_id': 46302,
                                       'unit_type': 'moon_goo',
                                       'volume': 10},
                   'Lavish Otavite': {'compressed_type_id': 46296,
                                      'compressed_volume': 10,
                                      'type_id': 46296,
                                      'unit_type': 'moon_goo',
                                      'volume': 10},
                   'Lavish Sperrylite': {'compressed_type_id': 46298,
                                         'compressed_volume': 10,
                                         'type_id': 46298,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Lavish Vanadinite': {'compressed_type_id': 46300,
                                         'compressed_volume': 10,
                                         'type_id': 46300,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Loparite': {'compressed_type_id': 45512,
                                'compressed_volume': 10,
                                'type_id': 45512,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Luminous Kernite': {'compressed_type_id': 28411,
                                        'compressed_volume': 0.19,
                                        'type_id': 17452,
                                        'unit_type': 'ore',
                                        'volume': 1.2},
                   'Lustrous Hedbergite': {'compressed_type_id': 46696,
                                           'compressed_volume': 0.47,
                                           'type_id': 46680,
                                           'unit_type': 'ore',
                                           'volume': 3},
                   'Magma Mercoxit': {'compressed_type_id': 28412,
                                      'compressed_volume': 0.1,
                                      'type_id': 17869,
                                      'unit_type': 'mercoxit',
                                      'volume': 40},
                   'Massive Scordite': {'compressed_type_id': 28428,
                                        'compressed_volume': 0.19,
                                        'type_id': 17464,
                                        'unit_type': 'ore',
                                        'volume': 0.15},
                   'Mercoxit': {'compressed_type_id': 28413,
                                'compressed_volume': 0.1,
                                'type_id': 11396,
                                'unit_type': 'mercoxit',
                                'volume': 40},
                   'Monazite': {'compressed_type_id': 45511,
                                'compressed_volume': 10,
                                'type_id': 45511,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Monoclinic Bistot': {'compressed_type_id': 28389,
                                         'compressed_volume': 4.4,
                                         'type_id': 17429,
                                         'unit_type': 'ore',
                                         'volume': 16},
                   'Obsidian Ochre': {'compressed_type_id': 28395,
                                      'compressed_volume': 4.2,
                                      'type_id': 17437,
                                      'unit_type': 'ore',
                                      'volume': 8},
                   'Omber': {'compressed_type_id': 28416,
                             'compressed_volume': 0.3,
                             'type_id': 1227,
                             'unit_type': 'ore',
                             'volume': 0.6},
                   'Onyx Ochre': {'compressed_type_id': 28396,
                                  'compressed_volume': 4.2,
                                  'type_id': 17436,
                                  'unit_type': 'ore',
                                  'volume': 8},
                   'Opulent Pyroxeres': {'compressed_type_id': 46702,
                                         'compressed_volume': 0.16,
                                         'type_id': 46686,
                                         'unit_type': 'ore',
                                         'volume': 0.3},
                   'Otavite': {'compressed_type_id': 45498,
                               'compressed_volume': 10,
                               'type_id': 45498,
                               'unit_type': 'moon_goo',
                               'volume': 10},
                   'Pellucid Crokite': {'compressed_type_id': 46693,
                                        'compressed_volume': 7.81,
                                        'type_id': 46677,
                                        'unit_type': 'ore',
                                        'volume': 16},
                   'Plagioclase': {'compressed_type_id': 28422,
                                   'compressed_volume': 0.15,
                                   'type_id': 18,
                                   'unit_type': 'ore',
                                   'volume': 0.35},
                   'Platinoid Omber': {'compressed_type_id': 46700,
                                       'compressed_volume': 0.3,
                                       'type_id': 46684,
                                       'unit_type': 'ore',
                                       'volume': 0.6},
                   'Pollucite': {'compressed_type_id': 45504,
                                 'compressed_volume': 10,
                                 'type_id': 45504,
                                 'unit_type': 'moon_goo',
                                 'volume': 10},
                   'Prime Arkonor': {'compressed_type_id': 28387,
                                     'compressed_volume': 8.8,
                                     'type_id': 17426,
                                     'unit_type': 'ore',
                                     'volume': 16},
                   'Prismatic Gneiss': {'compressed_type_id': 28399,
                                        'compressed_volume': 1.8,
                                        'type_id': 17866,
                                        'unit_type': 'ore',
                                        'volume': 5},
                   'Pristine Jaspet': {'compressed_type_id': 28407,
                                       'compressed_volume': 0.15,
                                       'type_id': 17449,
                                       'unit_type': 'ore',
                                       'volume': 2},
                   'Pristine White Glaze': {'compressed_type_id': 28441,
                                            'compressed_volume': 100.0,
                                            'type_id': 17976,
                                            'unit_type': 'ice',
                                            'volume': 1000},
                   'Pure Jaspet': {'compressed_type_id': 28408,
                                   'compressed_volume': 0.15,
                                   'type_id': 17448,
                                   'unit_type': 'ore',
                                   'volume': 2},
                   'Pyroxeres': {'compressed_type_id': 28424,
                                 'compressed_volume': 0.16,
                                 'type_id': 1224,
                                 'unit_type': 'ore',
                                 'volume': 0.3},
                   'Radiant Hemorphite': {'compressed_type_id': 28404,
                                          'compressed_volume': 0.86,
                                          'type_id': 17445,
                                          'unit_type': 'ore',
                                          'volume': 3},
                   'Replete Carnotite': {'compressed_type_id': 46304,
                                         'compressed_volume': 10,
                                         'type_id': 46304,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Replete Cinnabar': {'compressed_type_id': 46310,
                                        'compressed_volume': 10,
                                        'type_id': 46310,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Replete Pollucite': {'compressed_type_id': 46308,
                                         'compressed_volume': 10,
                                         'type_id': 46308,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Replete Zircon': {'compressed_type_id': 46306,
                                      'compressed_volume': 10,
                                      'type_id': 46306,
                                      'unit_type': 'moon_goo',
                                      'volume': 10},
                   'Resplendant Kernite': {'compressed_type_id': 46699,
                                           'compressed_volume': 0.19,
                                           'type_id': 46683,
                                           'unit_type': 'ore',
                                           'volume': 1.2},
                   'Rich Plagioclase': {'compressed_type_id': 28423,
                                        'compressed_volume': 0.15,
                                        'type_id': 17456,
                                        'unit_type': 'ore',
                                        'volume': 0.35},
                   'Scheelite': {'compressed_type_id': 45497,
                                 'compressed_volume': 10,
                                 'type_id': 45497,
                                 'unit_type': 'moon_goo',
                                 'volume': 10},
                   'Scintillating Hemorphite': {'compressed_type_id': 46697,
                                                'compressed_volume': 0.86,
                                                'type_id': 46681,
                                                'unit_type': 'ore',
                                                'volume': 3},
                   'Scordite': {'compressed_type_id': 28429,
                                'compressed_volume': 0.19,
                                'type_id': 1228,
                                'unit_type': 'ore',
                                'volume': 0.15},
                   'Sharp Crokite': {'compressed_type_id': 28393,
                                     'compressed_volume': 7.81,
                                     'type_id': 17432,
                                     'unit_type': 'ore',
                                     'volume': 16},
                   'Shimmering Chromite': {'compressed_type_id': 46303,
                                           'compressed_volume': 10,
                                           'type_id': 46303,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Shimmering Otavite': {'compressed_type_id': 46297,
                                          'compressed_volume': 10,
                                          'type_id': 46297,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Shimmering Sperrylite': {'compressed_type_id': 46299,
                                             'compressed_volume': 10,
                                             'type_id': 46299,
                                             'unit_type': 'moon_goo',
                                             'volume': 10},
                   'Shimmering Vanadinite': {'compressed_type_id': 46301,
                                             'compressed_volume': 10,
                                             'type_id': 46301,
                                             'unit_type': 'moon_goo',
                                             'volume': 10},
                   'Shining Loparite': {'compressed_type_id': 46317,
                                        'compressed_volume': 10,
                                        'type_id': 46317,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Shining Monazite': {'compressed_type_id': 46315,
                                        'compressed_volume': 10,
                                        'type_id': 46315,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Shining Xenotime': {'compressed_type_id': 46313,
                                        'compressed_volume': 10,
                                        'type_id': 46313,
                                        'unit_type': 'moon_goo',
                                        'volume': 10},
                   'Shining Ytterbite': {'compressed_type_id': 46319,
                                         'compressed_volume': 10,
                                         'type_id': 46319,
                                         'unit_type': 'moon_goo',
                                         'volume': 10},
                   'Silvery Omber': {'compressed_type_id': 28417,
                                     'compressed_volume': 0.3,
                                     'type_id': 17867,
                                     'unit_type': 'ore',
                                     'volume': 0.6},
                   'Smooth Glacial Mass': {'compressed_type_id': 28442,
                                           'compressed_volume': 100.0,
                                           'type_id': 17977,
                                           'unit_type': 'ice',
                                           'volume': 1000},
                   'Solid Pyroxeres': {'compressed_type_id': 28425,
                                       'compressed_volume': 0.16,
                                       'type_id': 17459,
                                       'unit_type': 'ore',
                                       'volume': 0.3},
                   'Sparkling Plagioclase': {'compressed_type_id': 46701,
                                             'compressed_volume': 0.15,
                                             'type_id': 46685,
                                             'unit_type': 'ore',
                                             'volume': 0.35},
                   'Sperrylite': {'compressed_type_id': 45499,
                                  'compressed_volume': 10,
                                  'type_id': 45499,
                                  'unit_type': 'moon_goo',
                                  'volume': 10},
                   'Spodumain': {'compressed_type_id': 28420,
                                 'compressed_volume': 28.0,
                                 'type_id': 19,
                                 'unit_type': 'ore',
                                 'volume': 16},
                   'Stable Veldspar': {'compressed_type_id': 46705,
                                       'compressed_volume': 0.15,
                                       'type_id': 46689,
                                       'unit_type': 'ore',
                                       'volume': 0.1},
                   'Sylvite': {'compressed_type_id': 45491,
                               'compressed_volume': 10,
                               'type_id': 45491,
                               'unit_type': 'moon_goo',
                               'volume': 10},
                   'Thick Blue Ice': {'compressed_type_id': 28443,
                                      'compressed_volume': 100.0,
                                      'type_id': 17975,
                                      'unit_type': 'ice',
                                      'volume': 1000},
                   'Titanite': {'compressed_type_id': 45496,
                                'compressed_volume': 10,
                                'type_id': 45496,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Triclinic Bistot': {'compressed_type_id': 28390,
                                        'compressed_volume': 4.4,
                                        'type_id': 17428,
                                        'unit_type': 'ore',
                                        'volume': 16},
                   'Twinkling Cobaltite': {'compressed_type_id': 46289,
                                           'compressed_volume': 10,
                                           'type_id': 46289,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Twinkling Euxenite': {'compressed_type_id': 46291,
                                          'compressed_volume': 10,
                                          'type_id': 46291,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Twinkling Scheelite': {'compressed_type_id': 46295,
                                           'compressed_volume': 10,
                                           'type_id': 46295,
                                           'unit_type': 'moon_goo',
                                           'volume': 10},
                   'Twinkling Titanite': {'compressed_type_id': 46293,
                                          'compressed_volume': 10,
                                          'type_id': 46293,
                                          'unit_type': 'moon_goo',
                                          'volume': 10},
                   'Vanadinite': {'compressed_type_id': 45500,
                                  'compressed_volume': 10,
                                  'type_id': 45500,
                                  'unit_type': 'moon_goo',
                                  'volume': 10},
                   'Veldspar': {'compressed_type_id': 28432,
                                'compressed_volume': 0.15,
                                'type_id': 1230,
                                'unit_type': 'ore',
                                'volume': 0.1},
                   'Viscous Pyroxeres': {'compressed_type_id': 28426,
                                         'compressed_volume': 0.16,
                                         'type_id': 17460,
                                         'unit_type': 'ore',
                                         'volume': 0.3},
                   'Vitreous Mercoxit': {'compressed_type_id': 28414,
                                         'compressed_volume': 0.1,
                                         'type_id': 17870,
                                         'unit_type': 'mercoxit',
                                         'volume': 40},
                   'Vitric Hedbergite': {'compressed_type_id': 28402,
                                         'compressed_volume': 0.47,
                                         'type_id': 17440,
                                         'unit_type': 'ore',
                                         'volume': 3},
                   'Vivid Hemorphite': {'compressed_type_id': 28405,
                                        'compressed_volume': 0.86,
                                        'type_id': 17444,
                                        'unit_type': 'ore',
                                        'volume': 3},
                   'White Glaze': {'compressed_type_id': 28444,
                                   'compressed_volume': 100.0,
                                   'type_id': 16265,
                                   'unit_type': 'ice',
                                   'volume': 1000},
                   'Xenotime': {'compressed_type_id': 45510,
                                'compressed_volume': 10,
                                'type_id': 45510,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Ytterbite': {'compressed_type_id': 45513,
                                 'compressed_volume': 10,
                                 'type_id': 45513,
                                 'unit_type': 'moon_goo',
                                 'volume': 10},
                   'Zeolites': {'compressed_type_id': 45490,
                                'compressed_volume': 10,
                                'type_id': 45490,
                                'unit_type': 'moon_goo',
                                'volume': 10},
                   'Zircon': {'compressed_type_id': 45503,
                              'compressed_volume': 10,
                              'type_id': 45503,
                              'unit_type': 'moon_goo',
                              'volume': 10}}

with open("baseOreData.json", "w") as f:
    json.dump(baseOreDataDict, f)
